module Tracing
  module Core
    # The trait implemented to collect trace data.
    #
    # A Subscriber is responsible for collecting and recording
    # trace data generated by spans and events.
    module Subscriber
      # Called when a new span is created.
      abstract def new_span(attrs : Span::Attributes) : Span::Id

      # Called when a span is entered.
      abstract def enter(id : Span::Id) : Nil

      # Called when a span is exited.
      abstract def exit(id : Span::Id) : Nil

      # Called when an event is recorded.
      abstract def event(event : Event) : Nil

      # Called when fields are recorded on a span.
      abstract def record(id : Span::Id, values : Span::Record) : Nil

      # Called when a follows-from relationship is established.
      abstract def record_follows_from(span : Span::Id, follows : Span::Id) : Nil

      # Returns true if a span or event with the given metadata would be enabled.
      abstract def enabled(metadata : Metadata) : Bool

      # Registers a new callsite with this subscriber.
      abstract def register_callsite(metadata : Metadata) : Callsite::Interest

      # Returns the highest level that this subscriber will enable.
      # Returns nil if no max has been configured.
      def max_level_hint : LevelFilter?
        nil
      end

      # Returns the subscriber's view of the current span.
      def current_span : Span::Current
        Span::Current.unknown
      end
    end

    # A subscriber that does nothing.
    class NoSubscriber
      include Subscriber

      def new_span(attrs : Span::Attributes) : Span::Id
        Span::Id.from_u64(1)
      end

      def enter(id : Span::Id) : Nil
      end

      def exit(id : Span::Id) : Nil
      end

      def event(event : Event) : Nil
      end

      def record(id : Span::Id, values : Span::Record) : Nil
      end

      def record_follows_from(span : Span::Id, follows : Span::Id) : Nil
      end

      def enabled(metadata : Metadata) : Bool
        false
      end

      def register_callsite(metadata : Metadata) : Callsite::Interest
        Callsite::Interest::SOMETIMES
      end
    end
  end
end
